firstcontributions/firstcontributions.github.io

src/components/ProjectList/listOfProjects.js
=> Added 4 projects to project list #1

src/components/ProjectList/listOfProjects.js
=> Add opensourcedesign to project list

ISSUE_TEMPLATE.md
=> Added ISSUE_TEMPLATE.md

src/components/ProjectList/listOfProjects.js
=> Added React Native to list of projects

src/components/ProjectList/listOfProjects.js
I added a valid link for Ruby koans card.  Reference to issue #25
=> logo image link in Ruby Koans card

src/components/ProjectList/css/project-cards.css
the cards width's bug in issue #15 is solved by adjusting the width of card in mobile view.
=> Fix width of cards in issue #15

src/components/LinkButton/LinkButton.jsx
Congrats on having the repo with with the [second-highest PR count](https://hacktoberfest.digitalocean.com/stats/)!
=> Edit href in LinkButton

src/components/ProjectList/listOfProjects.js
Updates the github URLs to include 'tags' for good first issue / beginner friendly etc, for URLs where this info was either missing or incorrect.
=> Update GitHub URLs to include relevant 'beginner' tags.

src/components/ProjectList/listOfProjects.js
https://proot-me.github.io
Bugs: https://github.com/firstcontributions/firstcontributions.github.io/issues/1
=> Add PRoot to list of projects

src/components/ProjectList/listOfProjects.js
=> Added rebus to project list

src/components/SocialShare/Facebook.jsx
Changed the Facebook share link to add Hacktobefest Hashtag to the Facebook card
=> Addresses #19

src/components/ProjectList/listOfProjects.js
Adds [Nextcloud](https://nextcloud.com). Please review @Roshanjossey @sara-02 :)
=> Add Nextcloud to project list

src/components/ProjectList/listOfProjects.js
@sara-02 one for you :)
https://opensourcediversity.org 🎉
=> Add Open Source Diversity to list of projects

src/components/SocialShare/SocialShare.jsx
Addresses #48 
Please review the change I have made to the file.
=> Updated SocialShare component to remove Google component import

src/components/ProjectList/CardsContainer.jsx
Addresses #47 
Please review the way I have implemented the random sorting of the list of projects. 
Random sorting happens only when there are no filters, in the case when a user puts in a filter, he will always see the same result in the same order.
=> Randomized sorting of cards

package-lock.json, src/components/LinkButton/__snapshots__/LinkButton.test.js.snap, src/components/ProjectList/__snapshots__/ProjectCards.test.js.snap, src/components/ProjectList/listOfProjects.js, src/components/SocialShare/Linkedin.test.js, src/components/SocialShare/__snapshots__/Linkedin.test.js.snap, src/components/SocialShare/__snapshots__/Twitter.test.js.snap
Just added another project repository Bitcoin along with others as my very first contribution. Also solved some bugs to make sure the tests are passing.
=> Added Project Bitcoin in the list

src/components/ProjectList/listOfProjects.js
Add Roc project, a toolkit for real-time audio streaming over the network:
https://github.com/roc-project/roc/
=> Add Roc to ProjectList

CONTRIBUTING.md
See the commit for more information.
=> Fix small issue in CONTRIBUTING.md

src/components/ProjectList/listOfProjects.js
=> Added Conda Project to the project list

src/components/ProjectList/css/project-cards.css
Added Text Transform to make the Tags uniform and this closes #71 and Style Sheet is formatted.
=> Added text transform to make the tags Uniform #71

src/components/ProjectList/listOfProjects.js
Adding Moby from the docker ecosystem to the list of projects to help solving #1
=> Adding Moby to project list

package-lock.json, src/components/ProjectList/listOfProjects.js
Hello @Roshanjossey  , 
I've added Laravel and Django to the list and also fixed a broken image link of RubyGems.
Please review this PR and merge if possible. 
Thank you.
=> added laravel and django 

src/components/ProjectList/listOfProjects.js
=> Add graph based projects

src/components/Navbar/Navbar.jsx
#96 
Youtube link added please review and add it .
=> Added YouTube Link

src/components/ProjectList/listOfProjects.js
<a align="center" href="https://github.com/airform/airform"><img width="100%" src="https://airform.io/static/icons/thumbnail.png" alt="Airform - Functional HTML forms for Front-End Developers."></a>
> Functional HTML forms for Front-End Developers.
What if you could use a service that gives you full control over the form, yet doesn’t require you to use anything on your server? Airform gives you the ability to create functional HTML forms without thinking about servers.
```
<form method="post" action="https://airform.io/your@email.com">
<input type="text" name="name">
<textarea name="message"></textarea>
<button>Send</button>
</form>
```
**Quick Tip:** The `action` attribute defines the location URL where the form's collected data should be sent when it is submitted. The `method` attribute …
=> Add Airform

src/components/ProjectList/listOfProjects.js
<a align="center" href="https://milligram.io"><img width="100%" src="https://milligram.io/images/thumbnail.png" alt="Milligram - A minimalist CSS framework"></a>
> A minimalist CSS framework.
Milligram provides a minimal setup of styles for a fast and clean starting point. Just it! **Only 2kb gzipped!** It's not about a UI framework. Specially designed for better performance and higher productivity with fewer properties to reset resulting in cleaner code. Hope you enjoy!
**Install with Bower**
```sh
$ bower install milligram
```
**Install with npm**
```sh
$ npm install milligram
```
**Install with Yarn**
```sh
$ yarn add milligram
```
- [Getting Started](https://milligram.io/#getting-started)
- [Typography](https://milligram.io/#typography)
- …
=> Add Milligram

src/components/SocialShare/__snapshots__/Linkedin.test.js.snap, src/components/SocialShare/__snapshots__/Twitter.test.js.snap
=> Fix the falling social share unit tests

src/App.css
Addresses #107
@sara-02 my old repository is get corrupted while I trying to fix the issue. So, I re-forked the firstcontributions.github.io and work on #107 again here. 
So, I request a new PR with the change and I will close the old PR.
Thanks
=> Fix mismatched property value in App.css

src/components/ProjectList/listOfProjects.js
=> Add game-of-life in listOfProjects

src/components/ProjectList/listOfProjects.js
=> Add Darktable to list of Projects

src/components/ProjectList/listOfProjects.js
Mattermost has a contributor program with
- list of help wanted issues ranging from easy to medium to hard tasks: https://github.com/mattermost/mattermost-server/contribute
- getting started guide for contributors: https://developers.mattermost.com/contribute/getting-started/
=> Add Mattermost to list of projects

src/components/Navbar/Navbar.css
=> Added Icons to Navbar

src/components/ProjectList/listOfProjects.js
Added Flutter for contribution in the First contribution.
=> Added Flutter for contributions

src/components/ProjectList/listOfProjects.js
Following Issue #1 Adds this great project as reference
=> Add Ansible to Project List

src/components/ProjectList/css/cards-container.css, src/components/ProjectList/css/search.css
search and filter were overlapping and cards in project list required some padding for mobile responsive design on Homepage
#128
=> overlapping and padding issues fixes

src/components/ProjectList/listOfProjects.js
- CSS-Art
- start-here-guidelines
=> chore: add more project to list

src/components/ProjectList/listOfProjects.js
Chat web app based on React JS, CSS.
=> Add chat web app to project list

src/components/ProjectList/listOfProjects.js
Fixes #136
Changed 3 urls to fix broken links in Hyper, Game of life, Gatsby projects.
=> fixed images urls on three items of the list that where broken

src/components/ProjectList/listOfProjects.js
=> fix: updated tags ,logo and link from Systers to AnitaB.org

src/components/ProjectList/listOfProjects.js
GitHub repo for ODK is moved now.
=> Updated ODK GitHub Link

src/components/ProjectList/listOfProjects.js
this is in context with the (here)[https://github.com/firstcontributions/firstcontributions.github.io/issues/153], 
**Problem**
Invlid logo URL used in
```
src/components/ProjectList/listOfProjects.js
```
- ifme [ Line No. - 464 ]
- Game of Life [ Line No. 660 ]
- Light Table [ Line No. 541 ]
**SOLUTIONS**
- above mentioned lines are resolved and fixed in this branch
=> [ Issue Fixed ] - #153 invalid or missing logos💡

src/components/Navbar/Navbar.jsx
https://github.com/firstcontributions/first-contributions/issues/33742
=> Updates Slack link

src/components/ProjectList/listOfProjects.js
Hi :)
to ease the start for beginners, MoveIt recently decided to introduce better-guided issues reserved for first-timers and labeled as "first-timer-only". We are an active and welcoming community and hope to help many new robotics enthusiasts getting started in the world of open-source robotics and motion planning :) Therefore, it would be great if you could add MoveIt to your awesome collection of beginner-friendly repositories.
Thanks in advance!
Cheers,
Sebastian
=> Adding MoveIt

src/components/Navbar/Navbar.jsx
Update Navbar from class component to functional component.
Class components are a bit deprecated, since they're not able to use hooks and other recent features of React. 
Updated the `Navbar/Navbar.jsx` file to be a functional component.
=> Update Navbar from class component to functional component

src/components/ProjectList/ProjectsCards.jsx
Update Card from class component to functional component.
Class components are a bit deprecated, since they're not able to use hooks and other recent features of React. 
Updated the `ProjectList/ProjectsCards.jsx` file to be a functional component.
=> Update Card from class component to functional component

src/components/ProjectList/listOfProjects.js
Add [leapcode](https://github.com/Leapcode-Open/leapcode-frontend) to the list of projects. :)
=> Add leapcode to list of projects

src/components/ProjectList/listOfProjects.js
We open sourced our product and have been accepting PRs since a few months. Would you like to add us to the list?
=> Add SimplQ

src/components/ProjectList/listOfProjects.js
Good. In this pull request I request to add two quite important projects ([https://github.com/firstcontributions/firstcontributions.github.io/issues/1](https://github.com/firstcontributions/firstcontributions.github.io/issues/1)) The first one is Rocky Linux, which is growing quite fast and we need a lot of people. The second of them is the mythical PHPmyadmin.
Thanks a lot.
A greeting
=> Add new proyects (Rocky Linux and PHPmyadmin)

src/components/ProjectList/listOfProjects.js
Add [React Testing Library](https://github.com/testing-library/react-testing-library) to the projects list.
Updated the `listOfProjects.js` file.
=> Add React Testing Library to the projects list

src/components/ProjectList/listOfProjects.js
Two of the tags just straight up didn't apply to the project (ruby & puppet -- we use neither)
=> Tweak tags to better fit Rocky Linux

src/components/ProjectList/listOfProjects.js
=> Add Navy Linux

src/components/ProjectList/listOfProjects.js
Added Hyper to the project list #173
=> added Hyper project to the projectlist

src/components/ProjectList/listOfProjects.js
This is my first open source project, I think it is a very good start point for beginners in Angular
=> Adding Litefy project to project list

src/components/ProjectList/listOfProjects.js
Adding '[Simple Icons](https://github.com/simple-icons/simple-icons)' to the list of projects.
=> Add Project: Simple Icons

src/components/SocialShare/Facebook.jsx, src/components/SocialShare/SocialShare.css
The footer with click-able buttons without hover effects doesn't give the feeling of press, so I added hover opacity effects to the footer buttons.
=> Added hover css effects to the footer buttons

src/App.jsx
Update App.jsx from class component to functional component.
Class components are a bit deprecated, since they're not able to use hooks and other recent features of React. 
Updated the `App.jsx` file to be a functional component.
=> Update App.jsx from class component to functional component

src/components/ProjectList/listOfProjects.js
They are gathering tons of issues and one that I mentioned below is an amazing resource for more information
See this issue [here](https://github.com/krishdevdb/reseter.css/issues/37)
=> Add Reseter.css

src/components/ProjectList/listOfProjects.js
Realised the image wasn't displaying correctly. Also linked directly to the 'good first issues' page.
=> Update Simple Icons

src/components/ProjectList/listOfProjects.js
This PR adds the Python pandas project to the src/components/ProjectList/listOfProjects.js file. Crucial library for data science, I'm surprised it wasn't there!
=> add pandas

src/components/ProjectList/listOfProjects.js, yarn.lock
- Added a new project (Mongodb).
- Also fixed a bug in tags property of Reseter.css project.
```diff
- `['css', 'sass' 'scss', 'less', 'stylus']`
+ `['css', 'sass', 'scss', 'less', 'stylus']`
```
=> Added a new project (MongoDB)

src/components/ProjectList/listOfProjects.js
This PR adds @spaceship-prompt to projects welcoming beginners.
=> Add spaceship-prompt

src/components/ProjectList/listOfProjects.js
✅ Fixes: #225 
🔍Findings: 
1. `Reseter.css` is maintained as an organization.
2. `React Native` branch is `main` and no longer `master`.
3. `Brackets` is an archived repository, that is, it is no longer maintained.
4. `Hyper` was duplicated. Have combined the details of the two.
=> Fix Broken Images & Remove Duplicate

src/components/ProjectList/listOfProjects.js
Updated the tags and description for the Oppia repository.
=> Update tags and description for Oppia

src/components/ProjectList/listOfProjects.js
=> remove archived project freeCodeCamp/mail-for-good

src/components/ProjectList/listOfProjects.js
This PR will add [CircuitVerse](https://github.com/CircuitVerse) to firstcontributions website.
=> added CircuitVerse org

src/components/Navbar/Navbar.jsx
=> Modified Slack invite link

src/components/Navbar/Navbar.css, src/components/Navbar/Navbar.jsx
Solve the issue #233. Find a similar issue on https://github.com/firstcontributions/first-contributions/issues/35814 and got the updated link (the same maintainer @Roshanjossey).
=> Slack link

src/components/Navbar/Navbar.css
create a better appealing experience when hovering over navbar
=> fix navbar

src/components/ProjectList/listOfProjects.js
This commit add a C# Project named Osu!.
Thank u!
=> Docs : Added  Osu! C# Project.

src/components/ProjectList/listOfProjects.js
This commit adds a Python Project named Salt.
Thank you!
=> Docs : Added Salt Python Project

src/components/ProjectList/listOfProjects.js
I'm adding my open source project, Ancient Beast, https://AncientBeast.com to the list of project using the repository
https://github.com/FreezingMoon/AncientBeast
This PR fixes https://github.com/firstcontributions/first-contributions/issues/60079
=> added AncientBeast.com to the list of projects

src/components/ProjectList/listOfProjects.js
=> New Project added

src/components/ProjectList/listOfProjects.js
Added two new projects, altair and appsmith to the project list.
=> added projects altair and appsmith

src/components/ProjectList/listOfProjects.js
Hey there! Just open-sourced a new project and am hoping to get it on here like another one of mine 😊 Let me know if there's anything else I need to do!
=> Add activist to listOfProjects.js

src/components/Navbar/Navbar.jsx
Slack joining link is updated for the website.
Fix: #338
=> updated the slack link for website

src/components/ProjectList/listOfProjects.js
I have updated the image link for the project pandas, which is not responding previsously.
old one:
new one:
=>  updated the  Image link  for pandas project which is not working

src/components/ProjectList/listOfProjects.js
[Feature]: Add default icon/image if the logo is not present #439
corrected 22 image logos in the src/components/ProjectList/listOfProjects.js file
note - my first open source contribution
=> added required image logos

src/components/ProjectList/listOfProjects.js, yarn.lock
This change resolves #416 by adding the project link attribute in JSON to  card object of "name: "aprenda-go-com-testes" 
Signed-off-by: Joby John
=>  added project link to aprenda-go-com-testes, now is clickable

src/components/ProjectList/listOfProjects.js
Some projects' description had words misspelled, this PR is fixing them #407 .
=> fix typos in list of projects

src/components/ProjectList/listOfProjects.js
--> added new links to corrupted links
=> issue:#410 loading images resloved

src/components/ProjectList/listOfProjects.js
Added Bokeh - Interactive Data Visualization in the browser, from Python. Address#2400
=> Added Bokeh to the project list. Please review.

src/components/ProjectList/listOfProjects.js
Add openSUSE and open issues for contribution
=> Update listOfProjects.js w/ openSUSE

src/components/ProjectList/listOfProjects.js
Hamilton has a bunch of issues that are appropriate for first time contributors who know how to write python. So adding to the list so that people can find this opportunity here too.
=> Adds Hamilton to list of projects

src/components/ProjectList/listOfProjects.js
Updates **listOfProjects.js** by adding Crucigrama (**Crosswords Puzzle Generator**) to projects list.
A very simple project in javascript intended for begginers, ideal for good first issue, with educational purposes.
[View repo](https://github.com/m0nt4ld0/crucigrama)
=> Added Crucigrama (Crosswords Puzzle Generator) to projects list

src/cra-project/components/ProjectList/listOfProjects.js
- removed the duplicate occurance of matplotlibm which was causing the project to break.
- /src/cra-project/components/ProjectList/listOfProjects.js
=> Fixed infinite loading on landing page 

src/cra-project/components/ProjectList/listOfProjects.js
fix crossword puzzle generator listing:
- fix spelling of "beginner"
- point logo image listing to new location
=> #498: fix crossword puzzle generator listing

src/components/App.astro
Title:
Add animated gradient to “contribution” text on landing page
Description:
This PR adds a smooth, moving gradient effect to the word “contribution” on the landing page to enhance visual appeal and draw attention.
Changes made:
Updated App-header > h1 span CSS to use a linear gradient with animation
Added @keyframes gradientShift for continuous gradient movement
Maintained responsiveness for screens ≤700px and ≤480px
Issue addressed:
Closes #<issue_number>
Preview:
Static gradient changed to animated moving gradient
Works on desktop and mobile view
=> added gradient in the contribution word at the front page
