- src/components/ProjectList/listOfProjects.js
Fixes #288 (https://github.com/techqueria/website/issues/288)
Issue: Techqueria.org was not a part of the https://firstcontributions.github.io/ page. Hence the above issue (#288) was raised.
Solution:
The required details for the card have been added to listOfProjects.js.
This closes an open issue for Techqueria by adding Techqueria.org to the FirstContributions.io site. 
To test:
1. Open https://firstcontributions.github.io/
2. On scrolling down, one of the cards should go by the name of "Techqueria.org" with the description "We're a community of Latinx professionals in the tech industry." along with the tags, image and github link as committed in listOfProjects.js
> #288 Added Techqueria to FirstContributions.io site

- src/components/ProjectList/css/project-cards.css
Simple CSS fix. Add margin 0 auto on .Card-Real-Link:link to center content on card.
> add margin 0 auto to center content on cards

- src/components/ProjectList/listOfProjects.js
Coala link was broken while navigating the project list. 
From Coala's [Get Involved](https://coala.io/#/getinvolved?lang=Python) page, the project is now directing newcomers to navigate to their [newcomer guide](https://coala.io/newcomer) through this link.
> Coala githubLink updated

- src/components/Navbar/Navbar.jsx
After noticing that the Slack invite link was expired on the website, I took the working link from the firstcontributions/first-contributions README file and copied it to here.
Fixes firstcontributions/first-contributions#19192
> Fix expired Slack link

- src/components/ProjectList/listOfProjects.js
The `/contribute` link, introduced by #58, is incorrect. It does not show expected issues, likely because Roc doesn't use the `good first issue` tag.
See also: #57.
> Fix GitHub link for Roc

- src/components/ProjectList/listOfProjects.js
Fun retro and Ruby gems are archived now.
Ruby koans doesn't have issues tab.
Hacktoberfest is a project that doesn't add value to open source community.
> Remove projects to improve user experience

- src/components/ProjectList/listOfProjects.js
TallyCTF is a scoring engine for capture the flag events released freely under the GPL-3.0 license.
> Add TallyCTF to list of projects

- src/components/ProjectList/listOfProjects.js
Add [RDoc::Generator::SolarFish](https://github.com/rbdoc/rdoc-generator-solarfish), single-page HTML5 generator for Ruby RDoc.
> Add RDoc::Generator::SolarFish

- src/components/ProjectList/listOfProjects.js
"Roc" was renamed to "Roc Toolkit", this PR updates the name and links.
> Update links to Roc

- src/components/ProjectList/listOfProjects.js
Add [Eclipse JKube](https://www.eclipse.org/jkube/) to the project list.
Specially crafted issues for beginners and first time committers to the project are labeled [first-timers-only](https://github.com/eclipse/jkube/labels/first-timers-only).
Preview:
> Add project Eclipse JKube

- src/components/ProjectList/listOfProjects.js
Hi there! 
Hoping that we can be added to this list. Scribe is still relatively new, but we're slowly making headway towards v2.0 that adds autocomplete and autosuggest - the last two must have features for a wider audience. The app's data is mostly from [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page) and Wikipedia, and we're a [featured project](https://www.mediawiki.org/wiki/New_Developers) for developers who are new to Wikimedia :) 
Hope that everything's in order for the PR, and thanks for this list!
> Add Scribe-iOS to listOfProjects.js

- src/components/ProjectList/listOfProjects.js
another PR for #258 
---
The [**Rocky Linux** project][2] is archived on Github.com, but remains an [active project elsewhere][3].
I'd argue that **Rocky Linux** is not a great project for First Contributions, since it requires quite a [sign-up process][1] and they state (on their archived github.com project), "We do not currently have any official crowdsourcing established." 
[1]: https://wiki.rockylinux.org/contributing/start/
[2]: https://github.com/rocky-linux/rocky#contributing
[3]: https://wiki.rockylinux.org/contributing/
> remove archived github.com repo

- src/components/ProjectList/listOfProjects.js
I've been updating the images for the repos and renamed the one that's referenced here. I think that doing the rounded icon would be best for the site anyway :)
Want to thank you again, btw! Looking at the traffic for Scribe, most of the external traffic is coming from firstcontributions.github.io 😊
> Update Scribe imageSrc in listOfProjects.js

- src/components/ProjectList/listOfProjects.js
Sorry for needing to update the information so soon after this was merged in #301. activist is still not showing up on firstcontributions, and I'm realizing that we changed the directory structure for the repo that has the logo image. I'm hoping that this will fix it and we'll be up! 
Aside from this I changed some of the metadata to better reflect the current state of the project :) Let me know if there could be another reason it's not showing up and I'd be happy to send along the appropriate changes! Thanks as always 😊
> Update activist info in listOfProjects.js

- src/components/ProjectList/ProjectsCards.jsx
Prior, the link redirects to the location of the link on the same tab as the homepage of https://firstcontributions.github.io. This modification adds <a target='blank'> to the card link and now enables the link to open another tab for the location the link redirects to preseving the tab of https://firstcontributions.github.io
> Add attribute target=blank to card link

- src/components/LinkButton/LinkButton.jsx
- src/components/LinkButton/__snapshots__/LinkButton.test.js.snap
I change the url of the button 'Get started' that point to the 'master' branch to other that point to 'main' branch fixing the redirect issue
fix issue #255
> Fix The "Get started" button link redirection #255

- src/components/ProjectList/listOfProjects.js
The link is expired. so, I have Updated the working URL and Image in ListOfProject.js file. Now it's working as expected.
1. Before Fix:
2. After fix:
> Missed projectLink in Aprenda lists

- src/components/ProjectList/listOfProjects.js
Add Gradle and SigNoz to listOfProjects.
Please review and advise.
Addresses #1.
> Add Gradle and SigNoz to listOfProjects

- src/App.css
- src/App.jsx
- src/components/LinkButton/LinkButton.css
- src/components/Navbar/Navbar.css
- src/components/ProjectList/css/project-cards.css
- src/components/SocialShare/SocialShare.css
> new-web-redesign

- src/components/ProjectList/listOfProjects.js
The link is expired. so, I have Updated the working URL and Image in ListOfProject.js file. Now it's working as expected.
**1. Before Fix:**
**2. After fix:**
>  ProjectLink in aprenda-go-com-testes

- src/components/ProjectList/listOfProjects.js
Hey @Roshanjossey 👋
Sending along the Android version of the iOS app Scribe - Language Keyboard, which is already on here. The [Scribe](https://github.com/scribe-org) community is a [Wikimedia project for new developers](https://www.mediawiki.org/wiki/New_Developers#Scribe) that's been growing recently :) We have tons of [good first issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) now for the Android app, and it'd be great if we could get your all's support with contributor acquisition! This PR also updates the Scribe-iOS entry so the projects are distinct 😊
Note that we're currently working on an MVP for Scribe-Android right now, so it's totally fine if you'd prefer me to send this along when we've finished the first …
> Add Scribe-Android to listOfProjects.js

- src/components/ProjectList/listOfProjects.js
This change removes the Atom project as the editor is no longer in active development and the repository has been archived since March 2023
> Removed atom

- src/cra-project/components/ProjectList/CardsContainer.jsx
Referring to #482, the issue was caused bysortArrayRandom being non-deterministic and the client rendering not matching the server.
- Add hydration state
- Add componentDidMount to set hydration to true, triggering re-render
- Update render() to return content only when hydration is true
I have tested this on my system, and the CSS now loads correctly with no error
> [Fix] #482 - Hydration Error in CardsContainer

- src/data/projects.js
#508 
the link mentioned for coala is not working or being maintained and is redirecting to some third party website
> bug:removed coala as its not working
